// GNULTE — network testing toolkit.
//
// Copyright (C) 2026 Neptune Productions.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	"gnulte-go/internal/monitor"
)

// writeReport renders report.txt (stats + ASCII timeline) and report.html
// (SVG latency charts) into dir.
func writeReport(dir string, res []monitor.Result, start, end time.Time) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "report.txt"),
		[]byte(reportTXT(res, start, end)), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(dir, "report.html"),
		[]byte(reportHTML(res, start, end)), 0o644); err != nil {
		return err
	}
	chownToInvoker(filepath.Join(dir, "report.txt"))
	chownToInvoker(filepath.Join(dir, "report.html"))
	chownToInvoker(dir)
	return nil
}

// chownToInvoker hands the path to the user that ran sudo, mirroring how the
// engine returns captured files.
func chownToInvoker(path string) {
	if os.Getuid() != 0 {
		return
	}
	uid, err1 := strconv.Atoi(os.Getenv("SUDO_UID"))
	gid, err2 := strconv.Atoi(os.Getenv("SUDO_GID"))
	if err1 == nil && err2 == nil {
		_ = os.Chown(path, uid, gid)
	}
}

func reportHeader(start, end time.Time) string {
	var b strings.Builder
	b.WriteString("GNULTE v" + version + "\n")
	b.WriteString("authorized network testing only\n")
	b.WriteString("generated " + start.Format("2006-01-02T15:04:05") + "\n")
	if !end.IsZero() {
		b.WriteString("duration  " + fmt.Sprintf("%.0f", end.Sub(start).Seconds()) + "s\n")
	}
	b.WriteString("\n")
	return b.String()
}

func statLine(ip string, st monitor.Stats) string {
	att := st.Count + st.Drops
	loss := 0.0
	if att > 0 {
		loss = float64(st.Drops) * 100 / float64(att)
	}
	avg := int64(0)
	if st.Count > 0 {
		avg = st.Total / int64(st.Count)
	}
	return fmt.Sprintf("  %-16s samples=%d min=%dms max=%dms avg=%dms loss=%.1f%%",
		ip, att, st.Min, st.Max, avg, loss)
}

func reportTXT(res []monitor.Result, start, end time.Time) string {
	var b strings.Builder
	b.WriteString(reportHeader(start, end))
	b.WriteString("targets: ")
	for i, r := range res {
		if i > 0 {
			b.WriteString(", ")
		}
		b.WriteString(r.IP)
	}
	b.WriteString("\n\n")
	for _, r := range res {
		b.WriteString(statLine(r.IP, r.Stats))
		b.WriteString("\n")
		b.WriteString(asciiChart(r.Stats.Samples))
		b.WriteString("\n")
	}
	return b.String()
}

// asciiChart renders an up-to-60 sample vertical timeline (10 rows high).
func asciiChart(samples []int) string {
	if len(samples) == 0 {
		return "    (no samples)\n"
	}
	n := len(samples)
	if n > 60 {
		samples = samples[n-60:]
		n = len(samples)
	}
	maxV := 100
	for _, v := range samples {
		if v > maxV {
			maxV = v
		}
	}
	if maxV <= 0 {
		maxV = 1
	}
	rows := 10
	var b strings.Builder
	for r := 0; r < rows; r++ {
		label := maxV - r*maxV/(rows-1)
		var line strings.Builder
		for _, v := range samples {
			idx := int(int64(maxV-v) * int64(rows-1) / int64(maxV))
			if idx == r {
				line.WriteByte('#')
			} else {
				line.WriteByte(' ')
			}
		}
		b.WriteString(fmt.Sprintf("%6d | %s\n", label, line.String()))
	}
	b.WriteString("        +" + strings.Repeat("-", n) + "\n")
	return b.String()
}

func reportHTML(res []monitor.Result, start, end time.Time) string {
	var b strings.Builder
	b.WriteString(`<!doctype html><html><head><meta charset="utf-8"><title>GNULTE report</title>`)
	b.WriteString(`<style>body{font-family:monospace;background:#111;color:#ddd;margin:2em}svg{background:#1a1a1a;margin:1em 0}h2{color:#4caf50}</style>`)
	b.WriteString("</head><body>\n")
	b.WriteString("<h1>GNULTE Network Test Report</h1>\n")
	b.WriteString("<p>authorized network testing only · Neptune Productions · generated " +
		start.Format("2006-01-02 15:04:05") + "</p>\n")
	if !end.IsZero() {
		b.WriteString("<p>duration: " + fmt.Sprintf("%.0f", end.Sub(start).Seconds()) + " s</p>\n")
	}
	for _, r := range res {
		st := r.Stats
		b.WriteString("<h2>" + htmlEscape(r.IP) + "</h2>\n")
		b.WriteString("<p>" + strings.TrimSpace(statLine(r.IP, st)[2:]) + "</p>\n")
		b.WriteString(svgChart(st.Samples))
	}
	b.WriteString("<p>generated by GNULTE v" + version + " — licensed under the GPLv3.</p>\n")
	b.WriteString("</body></html>\n")
	return b.String()
}

func svgChart(samples []int) string {
	if len(samples) == 0 {
		return "<svg width=\"800\" height=\"120\"></svg>\n"
	}
	if len(samples) == 1 {
		samples = append(samples, samples[0])
	}
	maxV := 100
	for _, v := range samples {
		if v > maxV {
			maxV = v
		}
	}
	W, H := 800, 160
	padL, padR, padT, padB := 40, 10, 10, 24
	plotW := W - padL - padR
	plotH := H - padT - padB
	var pts []string
	for i, v := range samples {
		x := padL + int(float64(i)*float64(plotW)/float64(len(samples)-1))
		y := padT + int(float64(maxV-v)*float64(plotH)/float64(maxV))
		pts = append(pts, fmt.Sprintf("%d,%d", x, y))
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("<svg width=\"%d\" height=\"%d\" viewBox=\"0 0 %d %d\">\n", W, H, W, H))
	// grid: 4 horizontal guide lines
	for g := 0; g <= 4; g++ {
		y := padT + int(float64(g)*float64(plotH)/4)
		val := maxV - int(float64(maxV)*float64(g)/4)
		b.WriteString(fmt.Sprintf("<line x1=\"%d\" y1=\"%d\" x2=\"%d\" y2=\"%d\" stroke=\"#333\" stroke-width=\"1\"/>\n", padL, y, W-padR, y))
		b.WriteString(fmt.Sprintf("<text x=\"%d\" y=\"%d\" fill=\"#888\" font-size=\"10\">%dms</text>\n", 4, y+1, val))
	}
	b.WriteString(fmt.Sprintf("<polyline points=\"%s\" fill=\"none\" stroke=\"#4caf50\" stroke-width=\"2\"/>\n", strings.Join(pts, " ")))
	b.WriteString(fmt.Sprintf("<text x=\"%d\" y=\"%d\" fill=\"#888\" font-size=\"10\">max %dms</text>\n", padL, H-6, maxV))
	b.WriteString("</svg>\n")
	return b.String()
}

func htmlEscape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", "\"", "&quot;")
	return r.Replace(s)
}
