// GNULTE — network testing toolkit.
//
// Copyright (C) 2026 Neptune Productions.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package main

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"

	"gnulte-go/internal/monitor"
)

// defaultSessionPath names the automatic report written when --report is not
// given (each test gets its own file).
func defaultSessionPath() string {
	return fmt.Sprintf("gnulte-session-%s.html", time.Now().Format("20060102-150405"))
}

// writeSessionReport renders a single self-contained HTML file combining the
// target statistics (SVG latency charts) with the full live console log — the
// entire history of the session, not just a summary.
func writeSessionReport(path string, log []string, res []monitor.Result, start, end time.Time) error {
	if err := os.WriteFile(path, []byte(sessionHTML(log, res, start, end)), 0o644); err != nil {
		return err
	}
	chownToInvoker(path)
	return nil
}

func sessionHTML(log []string, res []monitor.Result, start, end time.Time) string {
	var b strings.Builder
	b.WriteString(`<!doctype html><html><head><meta charset="utf-8">`)
	b.WriteString(`<meta name="viewport" content="width=device-width, initial-scale=1">`)
	b.WriteString(`<title>GNULTE session report</title>`)
	b.WriteString(`<style>
body{font-family:monospace;background:#111;color:#ddd;margin:1.5em;max-width:960px}
h1{color:#4caf50} h2{color:#4caf50;border-bottom:1px solid #2a2a2a;padding-bottom:.2em}
svg{background:#1a1a1a;margin:.5em 0;max-width:100%}
pre{background:#0d0d0d;border:1px solid #2a2a2a;padding:1em;overflow-x:auto;white-space:pre-wrap;word-break:break-word}
.meta{color:#999} .foot{color:#555;margin-top:2em;font-size:.85em}
kbd{background:#262626;padding:.1em .4em;border-radius:3px}
</style></head><body>`)
	b.WriteString("<h1>GNULTE Network Test Report</h1>\n")
	b.WriteString("<p class=\"meta\">authorized network testing only · Neptune Productions</p>\n")
	b.WriteString("<p>generated " + start.Format("2006-01-02 15:04:05") + "</p>\n")
	if !end.IsZero() {
		b.WriteString("<p>duration: " + fmt.Sprintf("%.0f", end.Sub(start).Seconds()) + " s</p>\n")
	}

	if len(res) == 0 {
		b.WriteString("<p>no target statistics captured.</p>\n")
	} else {
		b.WriteString("<h2>Target statistics</h2>\n")
		for _, r := range res {
			st := r.Stats
			b.WriteString("<h3>" + htmlEscape(r.IP) + "</h3>\n")
			b.WriteString("<p>" + htmlEscape(strings.TrimSpace(statLine(r.IP, st)[2:])) + "</p>\n")
			b.WriteString(svgChart(st.Samples))
		}
	}

	b.WriteString("<h2>Full log history</h2>\n")
	if len(log) == 0 {
		b.WriteString("<p>no console log captured (quiet run).</p>\n")
	} else {
		b.WriteString("<pre>\n")
		for _, l := range log {
			b.WriteString(htmlEscape(l))
			b.WriteString("\n")
		}
		b.WriteString("</pre>\n")
	}

	b.WriteString("<p class=\"foot\">generated by GNULTE v" + version + " — licensed under the GPLv3.<br>")
	b.WriteString("connectivity probed via ICMP echo with TCP-connect fallback on filtered targets.</p>\n")
	b.WriteString("</body></html>\n")
	return b.String()
}

func statLine(ip string, st monitor.Stats) string {
	att := st.Count + st.Drops
	loss := 0.0
	if att > 0 {
		loss = float64(st.Drops) * 100 / float64(att)
	}
	avg := int64(0)
	if st.Count > 0 {
		avg = st.Total / int64(st.Count)
	}
	return fmt.Sprintf("  %-16s samples=%d min=%dms max=%dms avg=%dms loss=%.1f%%",
		ip, att, st.Min, st.Max, avg, loss)
}

// svgChart renders a latency timeline so the report is readable without any
// JavaScript.
func svgChart(samples []int) string {
	if len(samples) == 0 {
		return "<svg width=\"800\" height=\"120\"></svg>\n"
	}
	if len(samples) == 1 {
		samples = append(samples, samples[0])
	}
	maxV := 100
	for _, v := range samples {
		if v > maxV {
			maxV = v
		}
	}
	W, H := 800, 160
	padL, padR, padT, padB := 40, 10, 10, 24
	plotW := W - padL - padR
	plotH := H - padT - padB
	var pts []string
	for i, v := range samples {
		x := padL + int(float64(i)*float64(plotW)/float64(len(samples)-1))
		y := padT + int(float64(maxV-v)*float64(plotH)/float64(maxV))
		pts = append(pts, fmt.Sprintf("%d,%d", x, y))
	}
	var b strings.Builder
	b.WriteString(fmt.Sprintf("<svg width=\"%d\" height=\"%d\" viewBox=\"0 0 %d %d\">\n", W, H, W, H))
	for g := 0; g <= 4; g++ {
		y := padT + int(float64(g)*float64(plotH)/4)
		val := maxV - int(float64(maxV)*float64(g)/4)
		b.WriteString(fmt.Sprintf("<line x1=\"%d\" y1=\"%d\" x2=\"%d\" y2=\"%d\" stroke=\"#333\" stroke-width=\"1\"/>\n", padL, y, W-padR, y))
		b.WriteString(fmt.Sprintf("<text x=\"%d\" y=\"%d\" fill=\"#888\" font-size=\"10\">%dms</text>\n", 4, y+1, val))
	}
	b.WriteString(fmt.Sprintf("<polyline points=\"%s\" fill=\"none\" stroke=\"#4caf50\" stroke-width=\"2\"/>\n", strings.Join(pts, " ")))
	b.WriteString(fmt.Sprintf("<text x=\"%d\" y=\"%d\" fill=\"#888\" font-size=\"10\">max %dms</text>\n", padL, H-6, maxV))
	b.WriteString("</svg>\n")
	return b.String()
}

// chownToInvoker hands the path to the user that ran sudo, mirroring how the
// engine returns captured files.
func chownToInvoker(path string) {
	if os.Getuid() != 0 {
		return
	}
	uid, err1 := strconv.Atoi(os.Getenv("SUDO_UID"))
	gid, err2 := strconv.Atoi(os.Getenv("SUDO_GID"))
	if err1 == nil && err2 == nil {
		_ = os.Chown(path, uid, gid)
	}
}

func htmlEscape(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", "\"", "&quot;")
	return r.Replace(s)
}
