// GNULTE — network testing toolkit.
//
// Copyright (C) 2026 Neptune Productions.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package main

import (
	"fmt"
	"os"
	"strings"

	"gnulte-go/internal/discover"
)

// scanMeta captures the scan parameters for the report header.
type scanMeta struct {
	Interface string
	SelfIP    string
	Gateway   string
	Subnet    string
}

// writeScanReport renders a single self-contained HTML file with the scan
// parameters, the discovered host table, and the entire session log history.
func writeScanReport(path string, log []string, rows []discover.Row, meta scanMeta) error {
	return os.WriteFile(path, []byte(scanSessionHTML(log, rows, meta)), 0o644)
}

func scanSessionHTML(log []string, rows []discover.Row, meta scanMeta) string {
	var b strings.Builder
	b.WriteString(`<!doctype html><html><head><meta charset="utf-8">`)
	b.WriteString(`<meta name="viewport" content="width=device-width, initial-scale=1">`)
	b.WriteString(`<title>GNULTE scan report</title>`)
	b.WriteString(`<style>
body{font-family:monospace;background:#111;color:#ddd;margin:1.5em;max-width:960px}
h1,h2{color:#4caf50} h2{border-bottom:1px solid #2a2a2a;padding-bottom:.2em}
table{border-collapse:collapse;margin:.5em 0;width:100%}
th,td{border:1px solid #2a2a2a;padding:.35em .6em;text-align:left;font-size:.95em}
th{background:#1a1a1a;color:#4caf50}
tr:nth-child(even){background:#161616}
pre{background:#0d0d0d;border:1px solid #2a2a2a;padding:1em;overflow-x:auto;white-space:pre-wrap;word-break:break-word}
.meta{color:#999} .foot{color:#555;margin-top:2em;font-size:.85em}
</style></head><body>`)
	b.WriteString("<h1>GNULTE LAN Scan Report</h1>\n")
	b.WriteString("<p class=\"meta\">authorized network testing only · Neptune Productions<br>\n")
	b.WriteString("generated by gnulte-scan v" + version + "</p>\n")

	b.WriteString("<h2>Session</h2>\n")
	b.WriteString(fmt.Sprintf("<p>%d host(s) responded.</p>\n", len(rows)))
	if meta.Interface != "" {
		b.WriteString(fmt.Sprintf("<p>interface: <b>%s</b> · this host: %s</p>\n", meta.Interface, htmlEsc(meta.SelfIP)))
	}
	if meta.Gateway != "" {
		b.WriteString(fmt.Sprintf("<p>gateway: <b>%s</b></p>\n", htmlEsc(meta.Gateway)))
	}
	if meta.Subnet != "" {
		b.WriteString(fmt.Sprintf("<p>scope: <b>%s</b></p>\n", htmlEsc(meta.Subnet)))
	}

	if len(rows) > 0 {
		// The Ports/OS column must be decided from every row, not just the
		// first (IP-sorted) one: a later host may be the only one deep-scanned,
		// and a column present for some rows but not others misaligns the table.
		hasDeep := false
		for _, r := range rows {
			if r.Ports != "" || r.OS != "" {
				hasDeep = true
				break
			}
		}
		b.WriteString("<h2>Discovered hosts</h2>\n<table>\n<tr><th>IP</th><th>MAC</th><th>Vendor</th><th>Hostname</th><th>Type</th>")
		if hasDeep {
			b.WriteString("<th>Ports / OS</th>")
		}
		b.WriteString("</tr>\n")
		for _, r := range rows {
			b.WriteString("<tr><td>" + htmlEsc(r.IP) + "</td>")
			b.WriteString("<td>" + htmlEsc(orDash(r.MAC)) + "</td>")
			b.WriteString("<td>" + htmlEsc(orDash(r.Vendor)) + "</td>")
			b.WriteString("<td>" + htmlEsc(orDash(r.Hostname)) + "</td>")
			b.WriteString("<td>" + htmlEsc(orDash(r.Type)) + "</td>")
			if hasDeep {
				extra := ""
				if r.Ports != "" {
					extra = r.Ports
					if r.OS != "" {
						extra += " · " + r.OS
					}
				} else if r.OS != "" {
					extra = r.OS
				}
				if len(r.Banners) > 0 {
					for _, b := range r.Banners {
						extra += "<br><small>" + htmlEsc(b) + "</small>"
					}
				}
				if r.ScanNote != "" {
					extra += "<br><small>" + htmlEsc(r.ScanNote) + "</small>"
				}
				b.WriteString("<td>" + orDash(extra) + "</td>")
			}
			b.WriteString("</tr>\n")
		}
		b.WriteString("</table>\n")
	}

	b.WriteString("<h2>Full log history</h2>\n")
	if len(log) == 0 {
		b.WriteString("<p>no console log captured (quiet run).</p>\n")
	} else {
		b.WriteString("<pre>\n")
		for _, l := range log {
			b.WriteString(htmlEsc(l))
			b.WriteString("\n")
		}
		b.WriteString("</pre>\n")
	}

	b.WriteString("<p class=\"foot\">generated by GNULTE v" + version + " — licensed under the GPLv3.</p>\n")
	b.WriteString("</body></html>\n")
	return b.String()
}

func htmlEsc(s string) string {
	r := strings.NewReplacer("&", "&amp;", "<", "&lt;", ">", "&gt;", "\"", "&quot;")
	return r.Replace(s)
}

func orDash(s string) string {
	if s == "" {
		return "-"
	}
	return s
}
