package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"gnulte-go/internal/discover"
)

func TestScanReportHTML(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "rep.html")
	rows := []discover.Row{
		{IP: "192.168.99.1", MAC: "AA:BB", Vendor: "TP-LINK", Hostname: "router", Type: "Router/Gateway"},
		{IP: "192.168.99.20", MAC: "CC:DD", Vendor: "Raspberry Pi", Hostname: "pi", Type: "Raspberry Pi", Ports: "22/closed, 80/open", OS: "Linux 5.15"},
	}
	log := []string{"  interface   wlan0  192.168.99.132",
		"  scan complete — 2 host(s) responded · 12:00:00",
		"  1G 192.168.99.1   AA:BB   TP-LINK   router   Router/Gateway",
	}
	meta := scanMeta{Interface: "wlan0", SelfIP: "192.168.99.132", Gateway: "192.168.99.1", Subnet: "192.168.99.0/24"}
	if err := writeScanReport(path, log, rows, meta); err != nil {
		t.Fatalf("writeScanReport: %v", err)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	html := string(raw)
	for _, want := range []string{
		"GNULTE LAN Scan Report",
		"192.168.99.1",
		"Raspberry Pi",
		"Full log history",
		"scan complete — 2 host(s) responded",
		"scope: <b>192.168.99.0/24</b>",
		"generated by gnulte-scan v" + version,
	} {
		if !strings.Contains(html, want) {
			t.Errorf("report missing %q", want)
		}
	}
	if strings.Contains(html, "<script") {
		t.Error("report should be static HTML with no scripting")
	}
}

func TestScanReportEscapesLog(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "rep.html")
	log := []string{"  <device>&\"quoted\""}
	if err := writeScanReport(path, log, nil, scanMeta{}); err != nil {
		t.Fatal(err)
	}
	raw, _ := os.ReadFile(path)
	if strings.Contains(string(raw), "<device>") {
		t.Error("log lines must be HTML-escaped")
	}
}
